-- Inserir produtos padrões
INSERT INTO produtos (id, titulo, preco, descricao, categoria, imagem, ativo) VALUES
(1, 'Lápis de Cor Multicolor 24 Cores', 21.5, 'Produto de excelente qualidade da marca Cor. Ideal para escola, escritório ou uso pessoal.', 'Lápis de Cor & Desenho', '/assets/produtos/produto_1.jpg', true),
(2, 'Lápis de Cor Multicolor 12 Cores', 9.9, 'Produto de excelente qualidade da marca Cor. Ideal para escola, escritório ou uso pessoal.', 'Lápis de Cor & Desenho', '/assets/produtos/produto_2.jpg', true),
(3, 'Lápis de Cor Leo&Leo 24 Cores', 12, 'Produto de excelente qualidade da marca Cor. Ideal para escola, escritório ou uso pessoal.', 'Lápis de Cor & Desenho', '/assets/produtos/produto_3.jpg', true),
(4, 'Lápis de Cor Leo&Leo 12 Cores', 7.9, 'Produto de excelente qualidade da marca Cor. Ideal para escola, escritório ou uso pessoal.', 'Lápis de Cor & Desenho', '/assets/produtos/produto_4.jpg', true),
(5, 'Lápis de Cor Big Leo&Leo 12 Cores', 14.9, 'Produto de excelente qualidade da marca Cor. Ideal para escola, escritório ou uso pessoal.', 'Lápis de Cor & Desenho', '/assets/produtos/produto_5.jpg', true),
(6, 'Canetinha Cis Hidrográfica 24 Cores', 27.9, 'Produto de excelente qualidade da marca Hidrográfica. Ideal para escola, escritório ou uso pessoal.', 'Lápis de Cor & Desenho', '/assets/produtos/produto_6.jpg', true),
(7, 'Canetinha Leo&Leo Hidrográfica 24 Cores', 16.9, 'Produto de excelente qualidade da marca Hidrográfica. Ideal para escola, escritório ou uso pessoal.', 'Lápis de Cor & Desenho', '/assets/produtos/produto_7.jpg', true),
(8, 'Canetinha Compactor Neo-Pen 12 Cores', 12.9, 'Produto de excelente qualidade da marca Neo-Pen. Ideal para escola, escritório ou uso pessoal.', 'Lápis de Cor & Desenho', '/assets/produtos/produto_8.jpg', true),
(9, 'Massinha de Modelar Pira 6 Cores', 3.5, 'Produto de excelente qualidade da marca Modelar. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_9.jpg', true),
(10, 'Massinha de Modelar Pira 12 Cores', 6, 'Produto de excelente qualidade da marca Modelar. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_10.jpg', true),
(11, 'Gizão de Cera Radex 12 Cores', 8.9, 'Produto de excelente qualidade da marca Cera. Ideal para escola, escritório ou uso pessoal.', 'Lápis de Cor & Desenho', '/assets/produtos/produto_11.jpg', true),
(12, 'Bloco Auto-Adesivo Post-It 500 folhas', 7.9, 'Produto de excelente qualidade da marca Post-It. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_12.jpg', true),
(13, 'Caneta Compactor Economic (Preta)', 1.5, 'Produto de excelente qualidade da marca Economic. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_13.jpg', true),
(14, 'Caneta Compactor Economic (Azul)', 1.5, 'Produto de excelente qualidade da marca Economic. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_14.jpg', true),
(15, 'Caneta Compactor Economic (Vermelha)', 1.5, 'Produto de excelente qualidade da marca Economic. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_15.jpg', true),
(16, 'Caneta Bic Cristal (Preta)', 1.7, 'Produto de excelente qualidade da marca Cristal. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_16.jpg', true),
(17, 'Caneta Bic Cristal (Azul)', 1.7, 'Produto de excelente qualidade da marca Cristal. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_17.jpg', true),
(18, 'Caneta Bic Cristal (Vermelha)', 1.7, 'Produto de excelente qualidade da marca Cristal. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_18.jpg', true),
(19, 'Caneta Cis Next Color (Unidade)', 2, 'Produto de excelente qualidade da marca Next. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_19.jpg', true),
(20, 'Caneta Marcadora Permanente (Preta)', 5.5, 'Produto de excelente qualidade da marca Permanente. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_20.jpg', true),
(21, 'Caneta Cis Spiro Colorida (Unidade)', 4.9, 'Produto de excelente qualidade da marca Spiro. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_21.jpg', true),
(22, 'Marca Texto Pastel Cis', 3.9, 'Produto de excelente qualidade da marca Pastel. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_22.jpg', true),
(23, 'Lapiseira Jocar Office 0.5mm', 6.5, 'Produto de excelente qualidade da marca Office. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_23.jpg', true),
(24, 'Lapiseira Jocar Office 0.7mm', 6.5, 'Produto de excelente qualidade da marca Office. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_24.jpg', true),
(25, 'Grafite Leo&Leo 0.5mm', 1.5, 'Produto de excelente qualidade da marca 0.5mm. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_25.jpg', true),
(26, 'Grafite Leo&Leo 0.7mm', 1.5, 'Produto de excelente qualidade da marca 0.7mm. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_26.jpg', true),
(27, 'Lápis Preto Maped de Escrever (HB)', 2.5, 'Produto de excelente qualidade da marca Maped. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_27.jpg', true),
(28, 'Lápis Preto Faber-Castell Max de Escrever', 1.5, 'Produto de excelente qualidade da marca Faber-Castell. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_28.jpg', true),
(29, 'Lápis Preto Leo&Leo de Escrever (HB)', 0.8, 'Produto de excelente qualidade da marca Leo&Leo. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_29.jpg', true),
(30, 'Elástico Mamuth (Pacote com 60)', 5, 'Produto de excelente qualidade da marca (Pacote. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_30.jpg', true),
(31, 'Pilha Rayovac AA (Unidade)', 1.8, 'Produto de excelente qualidade da marca AA. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_31.jpg', true),
(32, 'Pilha Rayovac AA (Pacote com 4)', 6, 'Produto de excelente qualidade da marca AA. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_32.jpg', true),
(33, 'Pilha Rayovac AAA (Unidade)', 1.5, 'Produto de excelente qualidade da marca AAA. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_33.jpg', true),
(34, 'Pilha Rayovac AAA (Pacote com 4)', 5, 'Produto de excelente qualidade da marca AAA. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_34.jpg', true),
(35, 'Borracha Mercur Colorida (Unidade)', 2.5, 'Produto de excelente qualidade da marca Colorida. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_35.jpg', true),
(36, 'Borracha Mercur Branca Record 20', 1.9, 'Produto de excelente qualidade da marca Branca. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_36.jpg', true),
(37, 'Borracha Mercur Branca Record 40', 1.5, 'Produto de excelente qualidade da marca Branca. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_37.jpg', true),
(38, 'Carnê do INSS', 4.9, 'Produto de excelente qualidade da marca INSS. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_38.jpg', true),
(39, 'Bloco de Recibo Comercial (Sem Cópia)', 2.5, 'Produto de excelente qualidade da marca Recibo. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_39.jpg', true),
(40, 'Bloco de Rascunho', 1.5, 'Produto de excelente qualidade da marca Rascunho. Ideal para escola, escritório ou uso pessoal.', 'Cadernos & Papéis', '/assets/produtos/produto_40.jpg', true),
(41, 'Cola Bastão Cis 19g', 3.9, 'Produto de excelente qualidade da marca Cis. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_41.jpg', true),
(42, 'Cola Bastão Cis 8g', 2.5, 'Produto de excelente qualidade da marca Cis. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_42.jpg', true),
(43, 'Bastão de Cola Quente Rendicolla Fino (Unidade)', 2.5, 'Produto de excelente qualidade da marca Cola. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_43.jpg', true),
(44, 'Bastão de Cola Quente Rendicolla Grosso (Unidade)', 3.5, 'Produto de excelente qualidade da marca Cola. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_44.jpg', true),
(45, 'Tinta Guache Escolar (Cores Sortidas)', 1.5, 'Produto de excelente qualidade da marca Escolar. Ideal para escola, escritório ou uso pessoal.', 'Lápis de Cor & Desenho', '/assets/produtos/produto_45.jpg', true),
(46, 'Pincel Redondo Leo&Leo Nº 04', 2.9, 'Produto de excelente qualidade da marca Leo&Leo. Ideal para escola, escritório ou uso pessoal.', 'Lápis de Cor & Desenho', '/assets/produtos/produto_46.jpg', true),
(47, 'Pincel Redondo Leo&Leo Nº 10', 3.2, 'Produto de excelente qualidade da marca Leo&Leo. Ideal para escola, escritório ou uso pessoal.', 'Lápis de Cor & Desenho', '/assets/produtos/produto_47.jpg', true),
(48, 'Apontador Duplo com Depósito Oval Leo&Leo', 4, 'Produto de excelente qualidade da marca com. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_48.jpg', true),
(49, 'Apontador Bloco Simples Leo&Leo', 1.9, 'Produto de excelente qualidade da marca Simples. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_49.jpg', true),
(50, 'Apontador Plástico Yolo (Cores Sortidas)', 1, 'Produto de excelente qualidade da marca Yolo. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_50.jpg', true),
(51, 'Cola Líquida New Magic 90g', 3.9, 'Produto de excelente qualidade da marca New. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_51.jpg', true),
(52, 'Cola Branca Escolar Make+ 40g', 2, 'Produto de excelente qualidade da marca Escolar. Ideal para escola, escritório ou uso pessoal.', 'Artes & Utilidades', '/assets/produtos/produto_52.jpg', true),
(53, 'Tesoura Escolar Sem Ponta Cis', 6.9, 'Produto de excelente qualidade da marca Sem. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_53.jpg', true),
(54, 'Etiqueta de Preço Nº4 22x12 (Unidade)', 0.9, 'Produto de excelente qualidade da marca Preço. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_54.jpg', true),
(55, 'Fita Adesiva Aderex 12x30', 2.5, 'Produto de excelente qualidade da marca Aderex. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_55.jpg', true),
(56, 'Fita Crepe Adesiva 18x10', 2.5, 'Produto de excelente qualidade da marca Adesiva. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_56.jpg', true),
(57, 'Fita Transparente Eurocel 18x50', 4, 'Produto de excelente qualidade da marca Eurocel. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_57.jpg', true),
(58, 'Fita Adesiva Afrontas 12x50', 3.5, 'Produto de excelente qualidade da marca Afrontas. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_58.jpg', true),
(59, 'Fita Larga Transparente Fit-Pel 45x45', 5, 'Produto de excelente qualidade da marca Transparente. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_59.jpg', true),
(60, 'Fita Dupla Face Adere 12x30', 7.9, 'Produto de excelente qualidade da marca Face. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_60.jpg', true),
(61, 'Fita Larga Marrom Fit-Pel 45x45', 6, 'Produto de excelente qualidade da marca Marrom. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_61.jpg', true),
(62, 'Calculadora de Mesa Dotad', 18.9, 'Produto de excelente qualidade da marca Mesa. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_62.jpg', true),
(63, 'Régua Plástica 30cm', 5.9, 'Produto de excelente qualidade da marca 30cm. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_63.jpg', true),
(64, 'Estilete Largo Profissional 18mm', 4, 'Produto de excelente qualidade da marca Profissional. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_64.jpg', true),
(65, 'Estilete Estreito Office 9mm', 2.5, 'Produto de excelente qualidade da marca Office. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_65.jpg', true),
(66, 'Lâmina para Estilete 18mm (Unidade)', 0.8, 'Produto de excelente qualidade da marca Estilete. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_66.jpg', true),
(67, 'Lâmina para Estilete 18mm (Caixa)', 5.9, 'Produto de excelente qualidade da marca Estilete. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_67.jpg', true),
(68, 'Lâmina para Estilete 9mm (Unidade)', 0.5, 'Produto de excelente qualidade da marca Estilete. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_68.jpg', true),
(69, 'Lâmina para Estilete 9mm (Caixa)', 3.9, 'Produto de excelente qualidade da marca Estilete. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_69.jpg', true),
(70, 'Clips Galvanizados Top 3/0', 3.5, 'Produto de excelente qualidade da marca Top. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_70.jpg', true),
(71, 'Grampeador Office Bazar 26/6', 12.5, 'Produto de excelente qualidade da marca Bazar. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_71.jpg', true),
(72, 'Caixa de Grampos Cis 26/6 com 1000 un.', 3.5, 'Produto de excelente qualidade da marca Grampos. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_72.jpg', true),
(73, 'Caderno Espiral Capa Dura 96 Folhas', 12.9, 'Produto de excelente qualidade da marca Capa. Ideal para escola, escritório ou uso pessoal.', 'Cadernos & Papéis', '/assets/produtos/produto_73.jpg', true),
(74, 'Caderno Espiral Capa Dura 200 Folhas', 22.9, 'Produto de excelente qualidade da marca Capa. Ideal para escola, escritório ou uso pessoal.', 'Cadernos & Papéis', '/assets/produtos/produto_74.jpg', true),
(75, 'Caderneta Espiral 40 Folhas 70x100mm', 2.5, 'Produto de excelente qualidade da marca 40. Ideal para escola, escritório ou uso pessoal.', 'Cadernos & Papéis', '/assets/produtos/produto_75.jpg', true),
(76, 'Caderneta Costurada 100x140mm', 4, 'Produto de excelente qualidade da marca 100x140mm. Ideal para escola, escritório ou uso pessoal.', 'Cadernos & Papéis', '/assets/produtos/produto_76.jpg', true),
(77, 'Caderno Capa Dura 1/4 96 Folhas', 7, 'Produto de excelente qualidade da marca Dura. Ideal para escola, escritório ou uso pessoal.', 'Cadernos & Papéis', '/assets/produtos/produto_77.jpg', true),
(78, 'Kit Canetas Compactor (Preta, Azul e Vermelha)', 3.5, 'Produto de excelente qualidade da marca Compactor. Ideal para escola, escritório ou uso pessoal.', 'Canetas & Escrita', '/assets/produtos/produto_78.jpg', true),
(79, 'Fita Corretiva Jocar Office', 6, 'Produto de excelente qualidade da marca Jocar. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_79.jpg', true),
(80, 'Corretivo Líquido New Magic', 2.9, 'Produto de excelente qualidade da marca New. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_80.jpg', true),
(81, 'Caneta Corretiva Jocar Office', 2.9, 'Produto de excelente qualidade da marca Jocar. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_81.jpg', true),
(82, 'Caderno Cartografia Capa Dura 48 Folhas', 10.9, 'Produto de excelente qualidade da marca Capa. Ideal para escola, escritório ou uso pessoal.', 'Cadernos & Papéis', '/assets/produtos/produto_82.jpg', true),
(83, 'Caderno Cartografia Capa Flexível 48 Folhas', 7, 'Produto de excelente qualidade da marca Capa. Ideal para escola, escritório ou uso pessoal.', 'Cadernos & Papéis', '/assets/produtos/produto_83.jpg', true),
(84, 'Caderno Capa Dura Brochura 96 Folhas', 13, 'Produto de excelente qualidade da marca Dura. Ideal para escola, escritório ou uso pessoal.', 'Cadernos & Papéis', '/assets/produtos/produto_84.jpg', true),
(85, 'Caderno Brochura Capa Flexível 60 Folhas', 9.5, 'Produto de excelente qualidade da marca Capa. Ideal para escola, escritório ou uso pessoal.', 'Cadernos & Papéis', '/assets/produtos/produto_85.jpg', true),
(86, 'Envelope Pardo A4', 0.9, 'Produto de excelente qualidade da marca A4. Ideal para escola, escritório ou uso pessoal.', 'Cadernos & Papéis', '/assets/produtos/produto_86.jpg', true),
(87, 'Pasta Polibras Fina', 5, 'Produto de excelente qualidade da marca Fina. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_87.jpg', true),
(88, 'Pasta Plástica Maleta 18x245x335mm', 7, 'Produto de excelente qualidade da marca Maleta. Ideal para escola, escritório ou uso pessoal.', 'Organização & Escritório', '/assets/produtos/produto_88.jpg', true);

-- Ajustar gerador de sequencial de ID dos produtos
SELECT setval(pg_get_serial_sequence('produtos', 'id'), coalesce(max(id), 1)) FROM produtos;

-- Inserir servicos padrões
INSERT INTO servicos (id, titulo, descricao, preco) VALUES
('s1', 'A4 Preto e Branco (Impressão)', 'Papel Sulfite 75g', 1.5),
('s2', 'A4 Preto e Branco (Cópia / Xerox)', 'Papel Sulfite 75g', 0.4),
('s3', 'A4 Colorido (Impressão)', 'Papel Sulfite 75g', 2),
('s4', 'A4 Colorido (Cópia / Xerox)', 'Papel Sulfite 75g', 1),
('s5', 'Meia A4', 'Papel Sulfite 75g', 5),
('s6', 'Papel Fotográfico', 'Impressão Colorida Premium', 5.5),
('s7', 'Papel 60 quilos', 'Impressão de Alta Gramatura', 5),
('s8', 'Papel Adesivo', 'Papel Adesivo Brilhante', 6),
('s9', 'Vinil Transparente', 'Adesivo Vinil Resistente', 8),
('s10', 'Plastificação A4', 'Polaseal Brilhante', 6),
('s11', 'Plastificação RG / CPF', 'Polaseal Brilhante', 4),
('s12', 'Encadernação Espiral', 'A cada 50 folhas (com Capa)', 4);
